# Generated by Django 3.2.6 on 2021-08-07 05:43

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('profile_pic', models.ImageField(upload_to='profile_pics')),
                ('email_address', models.EmailField(max_length=250, unique=True)),
                ('phone_number', models.IntegerField()),
                ('room_number', models.CharField(max_length=250)),
                ('subjects_taught', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Physics'), (2, 'Computer Science'), (3, 'History'), (4, 'Mathematics'), (5, 'Biology'), (6, 'Chemistry'), (7, 'English'), (8, 'Arabic'), (9, 'Geography')], max_length=5)),
            ],
        ),
    ]
