# Generated by Django 3.2.6 on 2021-08-07 06:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects_taught',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Physics'), (2, 'Computer Science'), (3, 'History'), (4, 'Mathematics'), (5, 'Biology'), (6, 'Chemistry'), (7, 'English'), (8, 'Arabic'), (9, 'Geography')], max_length=17),
        ),
    ]
